<?php
 
 $wc_chat_bots = array (
          'bot','crawl','spider','spyder','slurp','b-o-t','search','seek',
          'covario.com/ids','uni-leipzig.de/findlink','holmes/3','fetchagent',
          'htdig','archiver','ichiro/','lwebis','l.webis','larbin',
          'linkwalk','mabontland','mediapartners-google','mogimogi',
          'mvaclient','netresearchserver','newsgator','nutch',
          'nymesis','oegp','indexer','pompos','qseero','sbider',
          'scoutjet','scrubtheweb','semanticdiscover','shoula',
          'urltrend','sogou','worm','teoma','jeeves','tineye',
          'truwo','updated','bilbo','vortex','voyager','vyu2',
          'webcollage','websquash','factory','kototoi','borg',
          'scrapy'
 );

 $wc_chat_more_bots = array(
        '008\\/',        'A6-Indexer',  'Aboundex',  'Accoona-AI-Agent',
        'acoon',         'AddThis',     'ADmantX',   'AHC',
        'Airmail',       'Anemone',     'Arachmo',   'archive-com',
        'B-l-i-t-z-B-O-T',              'bibnum\.bnf',
        'biglotron',     'binlar',      'BingPreview',
        'boitho\.com-dc','BUbiNG',      'Butterfly\\/',
        'BuzzSumo',      'CapsuleChecker',
        'CC Metadata Scaper',           'Cerberian Drtrs',
        'changedetection',              'Charlotte', 'clips\.ua\.ac\.be',
        'CloudFlare-AlwaysOnline',      'coccoc',    'Commons-HttpClient',
        'convera',       'cosmos',      'Covario-IDS',
        'curl',          'CyberPatrol', 'DataparkSearch',
        'dataprovider',  'Digg',        'DomainAppender',
        'drupact',       'EARTHCOM',    'ec2linkfinder',
        'ElectricMonk',  'Embedly',     'europarchive\.org',
        'EventMachine HttpClient',      'ezooms',
        'eZ Publish Link Validator',    'facebookexternalhit',
        'Feedfetcher-Google',           'FeedValidator',
        'FindLinks',                    'findlink',
        'findthatfile',  'Flamingo_SearchEngine',    'fluffy',
        'getprismatic\.com',            'g00g1e\.net',
        'GigablastOpenSource',          'grub-client',
        'Genieo',        'Go-http-client','Google-HTTP-Java-Client',
        'Google favicon','Google Keyword Suggestion',  'heritrix',
        'Holmes',        'htdig',       'httpunit',    'httrack',
        'HubSpot Marketing Grader',     'ichiro',      'infegy',
        'igdeSpyder',    'InAGist',     'InfoWizards Reciprocal Link System PRO',
        'integromedb',   'IODC',        'IOI',         'ips-agent',
        'iZSearch',      'L\.webis',    'Larbin',      'libwww',
        'Link Valet',    'linkdex',     'LinkExaminer','LinkWalker',
        'Lipperhey Link Explorer',      'Lipperhey SEO Service',
        'LongURL API',   'ltx71',       'lwp-trivial', 'MegaIndex\.ru',
        'mabontland',    'MagpieRSS',   'Mediapartners-Google',
        'MetaURI',       'Mnogosearch', 'mogimogi',    'Morning Paper',
        'Mrcgiguy',      'MVAClient',   'Netcraft Web Server Survey',
        'netresearchserver',            'NewsGator',   'newsme',
        'NG-Search',     '^NING\\/',    'Notifixious', 'nutch',
        'NutchCVS',      'Nymesis',     'oegp',        'online link validator',
        'Online Website Link Checker',  'Orbiter',     'ow\.ly',
        'Ploetz \+ Zeller',             'page2rss',    'panscient',
        'Peew',          'phpcrawl',    'Pizilla',     'Plukkie',
        'Pompos',        'postano',     'PostPost',    'postrank',
        'proximic',      'PycURL',      'Python-httplib2',
        'python-requests',              'Python-urllib','Qseero',
        'Qwantify',      'Radian6',     'RebelMouse',   'REL Link Checker',
        'RetrevoPageAnalyzer',          'Riddler',      'Robosourcer',
        'Ruby',          'SBIder',      'ScoutJet',     'ScoutURLMonitor',
        'Scrapy',        'Scrubby',     'SearchSight',
        'semanticdiscovery',            'SEOstats',        'Seznam screenshot-generator',
        'ShopWiki',      'SiteBar',     'siteexplorer\.info',
        'slider\.com',   'slurp',       'Snappy',
        'sogou',         'speedy',      'Sqworm',       'StackRambler',
        'Stratagems Kumo',              'summify',      'teoma',
        'theoldreader\.com',            'TinEye',       'Traackr.com',
        'truwoGPS',      'tweetedtimes\.com',           'Twikle',
        'UnwindFetchor', 'updated',     'urlresolver',  'Validator\.nu\\/LV',
        'Vagabondo',     'Vivante Link Checker',        'Vortex',
        'voyager\\/',    'VYU2',        'W3C-checklink','W3C_CSS_Validator_JFouffa',
        'W3C_I18n-Checker',             'W3C-mobileOK', 'W3C_Unicorn',
        'W3C_Validator', 'WebIndex',    'Websquash\.com',
        'webcollage',    'webmon ',     'WeSEE:Search', 'wf84',
        'wget',          'WomlpeFactory',               'wotbox',
        'Xenu Link Sleuth',             'XML Sitemaps Generator',
        'Y!J-ASR',       'yacy',        'Yahoo Ad monitoring',
        'Yahoo Link Preview',           'Yahoo! Slurp China',
        'Yahoo! Slurp',  'YahooSeeker', 'YahooSeeker-Testing',
        'YandexImages',  'YandexMetrika',
        'YandexDirectDyn',  'yandex',   'yanga',        'yeti',
        'yoogliFetchAgent', 'Zao',      'ZyBorg',
        '[a-z0-9\\-_]*((?<!cu)bot|crawler|archiver|transcoder|spider)'

); //end array

$wc_botcheck_regex = "%(" . implode("|", array_merge($wc_chat_bots, $wc_chat_more_bots)) . ")%";

?>